source "https://rubygems.org"
gem "github-pages", ">= 224", group: :jekyll_plugins

# just-the-docs Jekyll theme
gem "just-the-docs", ">= 0.2.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?
